config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about", to: 'homes#about', as: :about


  resources :books, only: [:index, :show, :edit, :create, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  
  validates :title,  presence: true
  validates :body, length: { maximum: 200 }, presence: true
 
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, length: { minimum:2, maximum:20 }, uniqueness: { name: false }
  validates :introduction, length: { maximum: 50 }


  has_many :books, dependent: :destroy

  has_one_attached :profile_image



  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_log_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_log_out_path_for(resource)
    about_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
  


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    @book = Book.new
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def show
   @book = Book.find(params[:id])
   @user = @book.user
   @new_book = Book.new
  end

  def update
   @book = Book.find(params[:id])
   @book.update(book_params)
    if @book.save
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
end

#ストロングパラメータ
private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
  
 

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end 
end

  

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

#ストロングパラメータ
  private

  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        　　<%= @book.errors.count %>errors prohibited this obj from being saved:
        　　<ul>
          　　<% @book.errors.full_messages.each do |message| %>
          　　<li><%= message %></li>
          　<% end %>
          　</ul>
      <% end %>
      <%= form_with model: @book, method: :patch do |f| %>
        <div class="form-group">
         <label for="title">Title</label><br>
         <%= f.text_field :title %>
        </div>
        <div class="form-group">
         <label for="opinion">Opinion</label><br>
         <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>

    <%= link_to "Show", book_path(@book.id) %>
    |
    <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
          <%= image_tag current_user.get_profile_image %>
        <table class="table">
          <tbody>
            <tr>
              <th class="name">name</th>
              <th><%= current_user.name %></th>
            </tr>
            <tr>
              <th class="introduction">introduction</th>
              <th><%= current_user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
        <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-wrapper col-10 mx-auto" do %>
          <p><i class="fas fa-user-cog"></i></p>
        <% end %>
        </div>

        <h2 class="mt-3">New book</h2>
        <% if @book.errors.any? %>
        　　<%= @book.errors.count %>errors prohibited this obj from being saved:
        　　<ul>
          　　<% @book.errors.full_messages.each do |message| %>
          　　<li><%= message %></li>
          　<% end %>
          　</ul>
        <% end %>

          <%= form_with model: @book do |f| %>
          <div class="form-group">
            <%= f.label :title, "Title" %>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <%= f.label :body, "Opinion" %>
            <%= f.text_field :body %>
          </div>
          <button class="form-group btn btn-success">Create Book</button>
          <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th></th>
              </tr>
            </thead>
            <% @books.each do |book| %>
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                  <% end %>
                </td>
                <td>
                  <%= book.body %>
                </td>
              </tr>
            </tbody>
            <% end %>
        </table>
      </div>

app/views/books/show.html.erb
<p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

        <%= render "users/info", user: @user %>

        <h2 class="mt-3">New book</h2>
        <% if @book.errors.any? %>
        　　<%= @book.errors.count %>errors prohibited this obj from being saved:
        　　<ul>
          　　<% @book.errors.full_messages.each do |message| %>
          　　<li><%= message %></li>
          　<% end %>
          　</ul>
        <% end %>
          <%= form_with model: @new_book do |f| %>
          <div class="form-group">
            <%= f.label :title, "Title" %>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <%= f.label :body, "Opinion" %>
            <%= f.text_field :body %>
          </div>
          <button class="form-group btn btn-success">Create Book</button>
          <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                <%= image_tag @book.user.get_profile_image %>
                <% end %>
                <br>
                <%= link_to user_path(@user) do %>
                <%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path do %>
                <%= @book.title %>
                <% end %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <td>
                <% if @book.user == current_user %>
                <%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %><% end %>
              </td>
              <td>
                <% if @book.user == current_user %>
                <%= link_to "Destroy", book_path(@book.id), method: :delete, class:"btn btn-sm btn-danger" %><% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="low">
    <h1 class="px-3 mx-auto">
      welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>!!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="low">
    <div class="mx-auto col 11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>!!
      </h1>
      <p>In
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>,
      </p>
      <p>you can share and exchange your opnions,inpressions,and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <%= link_to 'Log in', new_user_session_path, class:'btn btn-info btn-block btn-sm' %><br>
        <%= link_to 'Sign up', new_user_registration_path, class:'btn btn-success btn-block btn-sm' %>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fontawesome-i2svg-active fontawesome-i2svg-conpete">
  <head>
    <title>Bookers2Ver2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navber-brand nav-link text-white" href="/" >
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse " id="navbarNavDropdown">
            <ul class="navbar-nav  ml-auto" >
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user.id), class: "nav-link text-white" do %>
                  <p><i class="fas fa-home"></i>Home</p>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class: "nav-link text-white" do %>
                  <p><i class="fas fa-users"></i>Users</p>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path, class: "nav-link text-white" do  %>
                  <p><i class="fas fa-book-open"></i>Books</p>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-white" do  %>
                  <p><i class="fas fa-sign-out-alt"></i>Log out</p>
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to root_path, class: "nav-link text-white" do %>
                  <p><i class="fas fa-home"></i>Home</p>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to about_path, class: "nav-link text-white" do  %>
                  <p><i class="fas fa-link"></i>About</p>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: "nav-link text-white" do  %>
                  <p><i class="fas fa-user-plus"></i>Sign up</p>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: "nav-link text-white" do  %>
                  <p><i class="fas fa-sign-in-alt"></i>Log in</p>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <p><%= notice %></p>
    <%= yield %>
    </main>
     <footer class="container mt-5">
       <div class="row">
         <div class="mx-auto">CopyRight Infratop.inc</div>
       </div>
     </div>
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
<h2>User info</h2>
<table class="table">
  <%= image_tag user.get_profile_image %>
  <tbody>
    <tr>
      <th class="name">name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th class="introduction">introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
  </table>
    <div class="row">
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-wrapper col-10 mx-auto" do %>
        <p><i class="fas fa-user-cog"></i></p>
      <% end %>
    </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        　　<%= @user.errors.count %>errors prohibited this obj from being saved:
        　　<ul>
          　　<% @user.errors.full_messages.each do |message| %>
          　　<li><%= message %></li>
          　<% end %>
          　</ul>
      <% end %>
      <%= form_with model: @user, method: :patch do |f| %>
        <div class="form-group">
          <label for="inputName">Name</label><br>
          <%= f.text_field :name, autofocus: true, id:"inputName" %>
        </div>
        <div class="form-group">
          <label for="inputImage">Image</label><br>
          <%= f.file_field :profile_image, accept: "image/*" %>
        </div>
        <div class="form-group">
          <label for="inputIntroduction">Introduction</label><br>
          <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        
        <%= render "info", user: @user %>



        <h2 class="mt-3">New book</h2>
        <% if @book.errors.any? %>
        　　<%= @book.errors.count %>errors prohibited this obj from being saved:
        　　<ul>
          　　<% @book.errors.full_messages.each do |message| %>
          　　<li><%= message %></li>
          　<% end %>
          　</ul>
        <% end %>
          <%= form_with model: @book do |f| %>
          <div class="form-group">
            <%= f.label :title, "Title" %>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <%= f.label :body, "Opinion" %>
            <%= f.text_field :body %>
          </div>
          <button class="form-group btn btn-success">Create Book</button>
          <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
          <table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td><%= image_tag user.get_profile_image %></td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            </tbody>
            <% end %>
        </table>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">

      <div class="col-md-3">

        <%= render "info", user: @user %>

        <h2 class="mt-3">New book</h2>
        <% if @book.errors.any? %>
        　　<%= @book.errors.count %>errors prohibited this obj from being saved:
        　　<ul>
          　　<% @book.errors.full_messages.each do |message| %>
          　　<li><%= message %></li>
          　<% end %>
          　</ul>
        <% end %>
          <%= form_with model: @book do |f| %>
          <div class="form-group">
            <%= f.label :title, "Title" %>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <%= f.label :body, "Opinion" %>
            <%= f.text_field :body %>
          </div>
          <button class="form-group btn btn-success">Create Book</button>
          <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path do %>
                <%= image_tag book.user.get_profile_image %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>